global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sentiment-mlops'

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics
    scrape_interval: 10s
